name: Ants Cluster
version: 0.0.1
description: Ants Cluster
dependencies:
  browser: any
  color: any
  game_loop:
      git: https://github.com/johnmccutchan/game_loop.git
dev_dependencies:
#  unittest: any
